export {default as Loader} from "./Loader"
export {default as Result} from "./Result"
export {default as Form} from "./Form"
export {default as Course} from "./Course"
export {default as OneExam} from "./OneExam"
export {default as TwoExams} from "./TwoExams"
export {default as Header} from "./Header"
